openapi: 3.0.0
info:
  title: User Authentication API
  version: "1.0"
paths:
  /api/users:
    post:
      summary: Authenticate a user
      operationId: authenticateUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
components:
  schemas:
    User:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
